In [1]:
# numpy 설치
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# numpy를 코드에서 사용할 수 있도록 준비
import numpy as np

In [3]:
# numpy 자료형
x1 = np.array([1, 2, 3]) # 자료형을 지정하지 않으면 데이터를 통해서 자동 선택
x2 = np.array([1, 2, 3], dtype='f') # np.array : numpy array 만들기
x3 = np.array([1, 2, 3], dtype=np.float16) 
 
x1.dtype, x2.dtype, x3.dtype # numpy_array.dtype : 자료형 반환

(dtype('int64'), dtype('float32'), dtype('float16'))

In [4]:
# numpy array 만들기 1

d = [1, 2, 3]
a = np.array(d)
print (type(d), type(a), d, a)


<class 'list'> <class 'numpy.ndarray'> [1, 2, 3] [1 2 3]


In [5]:
# numpy array 만들기 2
d = [[1, 2], [3, 4]]
a = np.array(d)
print(d)
print(a)
print(a.shape, a.ndim) # shape : 행, 열 등의 갯수, ndim : 차원

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
(2, 2) 2


In [6]:
# 복합자료형 : list - [], tuple - (), dict - {}

a = [1] # a는 list
b1 = (1) # b1은 int : ()를 연산자 우선순위 결정 도구 해석
b2 = (1,) # b2는 ? : ()를 튜플 생성 도구 해석
c = (1 + 3) * 4
print(type(a), type(b1), type(b2))

<class 'list'> <class 'int'> <class 'tuple'>


In [7]:
# numpy array 만들기 3

d = [1, 2, 3, 4, 5]
a1 = np.array(d)
a2 = np.array(d, ndmin=2)
print (a1, a1.shape, a1.ndim)
print (a2, a2.shape, a2.ndim)


[1 2 3 4 5] (5,) 1
[[1 2 3 4 5]] (1, 5) 2


In [8]:
# numpy array 차원 정보 사용

a = np.array([[1,2,3],[4,5,6]])
print(a, a.shape) 

a.shape = (3, 2) # a를 변경
print(a, a.shape)

a2 = np.array([[1,2,3],[4,5,6]])
a3 = a2.reshape(3, 2) # reshape은 a2를 변경하지 않습니다. -> reshape된 새 배열을 반환
print (a3, a2.shape, a3.shape) 

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2]
 [3 4]
 [5 6]] (2, 3) (3, 2)


In [14]:
# numpy array 생성 함수 1

x = np.ones([3,5], dtype=int) # 각 값이 1인 3행 5열 배열 만들기
print(x)

x = np.zeros([3,5], dtype=int) # 각 값이 0인 3행 5열 배열 만들기
print(x)

x = np.empty([7,4], dtype=int) # 각 값이 ?인 3행 5열 배열 만들기
print(x)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[                   0      140730677535216                  191
                    -1]
 [ 4189022085447885435  8101260420555416096  2340008625568817273
  -5122100670961506325]
 [ 7236823280293978288  3611935491644996896  2318285220974108716
   4404574730101480757]
 [ 7021800530740538912  3630304116747806841  8241919853483539744
   7935391352114209138]
 [ 6640894364961303908  2891438978336190574  8299625456511758689
   3558160555651916136]
 [ 7952276591925816878  7000881305188135536  7526410196178971698
   3328829865391911009]
 [ 2481021777726760046  8458716092899139628  8462091486378289524
     35244983642649710]]


In [ ]:
# numpy array 생성 함수 2

x = [1,2,3]
a = np.asarray(x)
print (a)




[1 2 3]


In [ ]:
# numpy array 생성 함수 3

x1 = range(10, 20, 2)       # 반복자 반환 ( 값의 목록을 반환하지 않습니다 )
x2 = np.arange(10, 20, 2)   # numpy array 형식의 값 목록을 반환
print(x1) # 반복자이기 때문에 바로 출력할 수 없습니다. - 반복문으로 각 값을 읽어야 합니다.
print(list(x1))
print(x2) 

range(10, 20, 2)
[10, 12, 14, 16, 18]
[10 12 14 16 18]
