In [1]:
# numpy 설치
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
# numpy를 코드에서 사용할 수 있도록 준비
import numpy as np

In [3]:
# numpy 자료형
x1 = np.array([1, 2, 3]) # 자료형을 지정하지 않으면 데이터를 통해서 자동 선택
x2 = np.array([1, 2, 3], dtype='f') # np.array : numpy array 만들기
x3 = np.array([1, 2, 3], dtype=np.float16) 
 
x1.dtype, x2.dtype, x3.dtype # numpy_array.dtype : 자료형 반환

(dtype('int64'), dtype('float32'), dtype('float16'))

In [4]:
# numpy array 만들기 1

d = [1, 2, 3]
a = np.array(d)
print (type(d), type(a), d, a)


<class 'list'> <class 'numpy.ndarray'> [1, 2, 3] [1 2 3]


In [5]:
# numpy array 만들기 2
d = [[1, 2], [3, 4]]
a = np.array(d)
print(d)
print(a)
print(a.shape, a.ndim) # shape : 행, 열 등의 갯수, ndim : 차원

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
(2, 2) 2


In [6]:
# 복합자료형 : list - [], tuple - (), dict - {}

a = [1] # a는 list
b1 = (1) # b1은 int : ()를 연산자 우선순위 결정 도구 해석
b2 = (1,) # b2는 ? : ()를 튜플 생성 도구 해석
c = (1 + 3) * 4
print(type(a), type(b1), type(b2))

<class 'list'> <class 'int'> <class 'tuple'>


In [7]:
# numpy array 만들기 3

d = [1, 2, 3, 4, 5]
a1 = np.array(d)
a2 = np.array(d, ndmin=2)
print (a1, a1.shape, a1.ndim)
print (a2, a2.shape, a2.ndim)


[1 2 3 4 5] (5,) 1
[[1 2 3 4 5]] (1, 5) 2


In [8]:
# numpy array 차원 정보 사용

a = np.array([[1,2,3],[4,5,6]])
print(a, a.shape) 

a.shape = (3, 2) # a를 변경
print(a, a.shape)

a2 = np.array([[1,2,3],[4,5,6]])
a3 = a2.reshape(3, 2) # reshape은 a2를 변경하지 않습니다. -> reshape된 새 배열을 반환
print (a3, a2.shape, a3.shape) 

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2]
 [3 4]
 [5 6]] (2, 3) (3, 2)


In [9]:
# numpy array 생성 함수 1

x = np.ones([3,5], dtype=int) # 각 값이 1인 3행 5열 배열 만들기
print(x)

x = np.zeros([3,5], dtype=int) # 각 값이 0인 3행 5열 배열 만들기
print(x)

x = np.empty([7,4], dtype=int) # 각 값이 ?인 3행 5열 배열 만들기
print(x)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[       1816075569544                  191                    0
                     0]
 [   18296268623183872  4189022085447885435  8101260420555416096
   2340008625568817273]
 [-5122100670961506325  7236823280293978288  3611935491644996896
   2318285220974108716]
 [ 4404574730101480757  7021800530740538912  3630304116747806841
   8241919853483539744]
 [ 7935391352114209138  6640894364961303908  2891438978336190574
   8299625456511758689]
 [ 3558160555651916136  7952276591925816878  7000881305188135536
   7526410196178971698]
 [ 3328829865391911009  2481021777726760046  8458716092899139628
   8462091486378289524]]


In [10]:
# numpy array 생성 함수 2

x = [1,2,3]
a = np.asarray(x)
print (a)




[1 2 3]


In [11]:
# numpy array 생성 함수 3

x1 = range(10, 20, 2)       # 반복자 반환 ( 값의 목록을 반환하지 않습니다 )
x2 = np.arange(10, 20, 2)   # numpy array 형식의 값 목록을 반환
print(x1) # 반복자이기 때문에 바로 출력할 수 없습니다. - 반복문으로 각 값을 읽어야 합니다.
print(list(x1))
print(x2) 

range(10, 20, 2)
[10, 12, 14, 16, 18]
[10 12 14 16 18]


In [12]:
# numpy array 생성 함수 4

a = np.linspace(1.0, 2.0, num=5)
print (a)

x = np.linspace(10, 20, 5, endpoint=False)
print (x)

x = np.linspace(1, 2, 5, retstep=True)
print (x) 


[1.   1.25 1.5  1.75 2.  ]
[10. 12. 14. 16. 18.]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25))


In [13]:
# 인덱싱과 슬라이싱 1

a = np.arange(10)
s = slice(2,7,2) # 슬라이싱 규칙 만들기 (2에서 7까지 2씩 증가)
print(a)
print(a[s])

# a = np.arange(10) # == np.arange(0, 10)
a = np.arange(0, 10)
b = a[2:7:2] # [2:7:2] == slice(2, 7, 2)
print (b)

a = np.arange(10)
print(a[4])


[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[2 4 6]
4


In [14]:
# 인덱싱과 슬라이싱 2

d = [[1,2,3],[3,4,5],[4,5,6]]
a = np.array(d)

print(d)
print(a)

# 1. 1차원에서는 인덱싱 사용 방법 동일
print(d[1], a[1])

# 2. 1차원에서는 슬라이싱 사용 방법 동일
print(d[1:], a[1:])

# 3. 2차원 이상에서 인덱싱 사용 방법 차이
print(d[1][2], a[1, 2])

# 4. 2차원 이상에서 슬라이싱 사용 방법 차이
print(d[1][1:], a[1, 1:])

# 5. 2차원 이상에서 슬라이싱 사용 방법 차이 2 - 
print(d[1:][1:])
print(a[1:, 1:])


[[1, 2, 3], [3, 4, 5], [4, 5, 6]]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
[3, 4, 5] [3 4 5]
[[3, 4, 5], [4, 5, 6]] [[3 4 5]
 [4 5 6]]
5 5
[4, 5] [4 5]
[[4, 5, 6]]
[[4 5]
 [5 6]]


In [15]:
# 1차원 리스트를 2차원 배열로 변경 1
d = [1, 2, 3, 4, 5, 6, 7, 8, 9]

a = np.array(d)
b = a.reshape(3, 3)
print(b)

# 1차원 리스트를 2차원 배열로 변경 2
a2 = np.arange(1, 10).reshape(3, 3)
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
# 인덱싱과 슬라이싱 3

x = np.array([[1, 2], [3, 4], [5, 6]])
print(x)
y = x[[0,1,2], [0,1,0]] # (0행, 0열), (1행, 1열), (2행, 0열)
print (y)


[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [17]:
# 인덱싱과 슬라이싱 4

x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print(x)
z = x[1:4, 1:3]
print (z)
y = x[1:4, [1,2]]
print (y)


[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]
[[ 4  5]
 [ 7  8]
 [10 11]]


In [18]:
# 인덱싱과 슬라이싱 5

x = np.array([[ 0, 1, 2],[ 3, 4, 5],[ 6, 7, 8],[ 9, 10, 11]])
print(x)

print(x > 5)

print(x[x > 5]) # 각 값의 위치에 True, False를 기준으로 True인 데이터만 뽑기

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[False False False]
 [False False False]
 [ True  True  True]
 [ True  True  True]]
[ 6  7  8  9 10 11]


In [19]:
# 인덱싱과 슬라이싱 6

a = np.array([np.nan, 1,2,np.nan,3,4,5]) # np.nan : 결측치를 표현하는 값
print(a)
is_mv = np.isnan(a) # isnan : np.nan이면 True 아니면 False
print(is_mv)
is_not_mv = ~is_mv # ~ : 배열의 각 True 또는 False값을 반대 값으로 변환
print(is_not_mv)

print(a[is_not_mv])


[nan  1.  2. nan  3.  4.  5.]
[ True False False  True False False False]
[False  True  True False  True  True  True]
[1. 2. 3. 4. 5.]


In [20]:
# np.isnan : np.nan이면 True 아니면 False

# np.isnan의 반대 기능 함수 ?
print( ~np.isnan([np.nan, 1,2,np.nan,3,4,5]) )
print( np.isfinite([np.nan, 1,2,np.nan,3,4,5]) ) # np.isfinite : np.nan, np.inf 이면 False 아니면 True

# ~ 연산 내용
print(~np.array([False,  True,  True, False,  True,  True,  True])) # ~ : bool인 경우 True->False, False-True
print(~np.array([1, 5, -4])) # ~ : 정수인 경우 -원래값 - 1

[False  True  True False  True  True  True]
[False  True  True False  True  True  True]
[ True False False  True False False False]
[-2 -6  3]


In [21]:
# 리스트와 numpy array의 연산 차이

d1 = [1,2,3,4]
d2 = [10,20,30,40]
a = np.array(d1)
b = np.array(d2)
c1 = a + b      # numpy array간 + 연산 ( 요소별 연산 )
c2 = d1 + d2    # list간 + 연산 ( 두 리스트 결합 )
print(c1, c2)

print(a * b)    # numpy array간 + 연산 ( 요소별 연산 )
# print(d1 * d2)  # list간 * 연산 ( 오류 : 지원하지 않음 )


[11 22 33 44] [1, 2, 3, 4, 10, 20, 30, 40]
[ 10  40  90 160]


In [22]:
# 브로드캐스팅

a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])
print (a + b)


[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [23]:
# 다차원 배열을 1차원 처럼 사용하는 방법

a = np.arange(0,60,5)
a = a.reshape(3,4)
print(a)

for x in a:
    print(x, end=' ')

print()

for x in np.nditer(a): # 2차원 배열 -> 1차원 처럼 순회
    print(x, end=' ')

print()
print(a.size) # size: 모든 요소의 갯수
for x in a.reshape(a.size): # 2차원 배열 -> 1차원 배열로 만들고 -> 순회
    print(x, end=' ')


[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]
[ 0  5 10 15] [20 25 30 35] [40 45 50 55] 
0 5 10 15 20 25 30 35 40 45 50 55 
12
0 5 10 15 20 25 30 35 40 45 50 55 

In [24]:
# 하나의 numpy array에는 같은 자료형의 데이터만 저장 가능
a = np.array([1, 2, 3, 4, 5, 'hello'])

print(a)

['1' '2' '3' '4' '5' 'hello']
