In [3]:
# numpy 설치
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
# numpy를 코드에서 사용할 수 있도록 준비
import numpy as np

In [5]:
# numpy 자료형
x1 = np.array([1, 2, 3]) # 자료형을 지정하지 않으면 데이터를 통해서 자동 선택
x2 = np.array([1, 2, 3], dtype='f') # np.array : numpy array 만들기
x3 = np.array([1, 2, 3], dtype=np.float16) 
 
x1.dtype, x2.dtype, x3.dtype # numpy_array.dtype : 자료형 반환

(dtype('int64'), dtype('float32'), dtype('float16'))

In [6]:
# numpy array 만들기 1

d = [1, 2, 3]
a = np.array(d)
print (type(d), type(a), d, a)


<class 'list'> <class 'numpy.ndarray'> [1, 2, 3] [1 2 3]


In [7]:
# numpy array 만들기 2
d = [[1, 2], [3, 4]]
a = np.array(d)
print(d)
print(a)
print(a.shape, a.ndim) # shape : 행, 열 등의 갯수, ndim : 차원

[[1, 2], [3, 4]]
[[1 2]
 [3 4]]
(2, 2) 2


In [8]:
# 복합자료형 : list - [], tuple - (), dict - {}

a = [1] # a는 list
b1 = (1) # b1은 int : ()를 연산자 우선순위 결정 도구 해석
b2 = (1,) # b2는 ? : ()를 튜플 생성 도구 해석
c = (1 + 3) * 4
print(type(a), type(b1), type(b2))

<class 'list'> <class 'int'> <class 'tuple'>


In [9]:
# numpy array 만들기 3

d = [1, 2, 3, 4, 5]
a1 = np.array(d)
a2 = np.array(d, ndmin=2)
print (a1, a1.shape, a1.ndim)
print (a2, a2.shape, a2.ndim)


[1 2 3 4 5] (5,) 1
[[1 2 3 4 5]] (1, 5) 2


In [10]:
# numpy array 차원 정보 사용

a = np.array([[1,2,3],[4,5,6]])
print(a, a.shape) 

a.shape = (3, 2) # a를 변경
print(a, a.shape)

a2 = np.array([[1,2,3],[4,5,6]])
a3 = a2.reshape(3, 2) # reshape은 a2를 변경하지 않습니다. -> reshape된 새 배열을 반환
print (a3, a2.shape, a3.shape) 

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[[1 2]
 [3 4]
 [5 6]] (2, 3) (3, 2)


In [11]:
# numpy array 생성 함수 1

x = np.ones([3,5], dtype=int) # 각 값이 1인 3행 5열 배열 만들기
print(x)

x = np.zeros([3,5], dtype=int) # 각 값이 0인 3행 5열 배열 만들기
print(x)

x = np.empty([7,4], dtype=int) # 각 값이 ?인 3행 5열 배열 만들기
print(x)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[[23925768161198179 32370111954616435 30681274979450972 18296268630392929]
 [27303364806049904 21392493373358196 30399714103066735 31244212046397532]
 [30681189080760423 34058815785402483 30962724186357876 32651616994721884]
 [14355696265920616 21392493370212401 32370017465139305 12666807751278697]
 [30118247716159600 32370056120172641 34058953225207900 28992352104808567]
 [25896191786221669 28992352104808567 25896191786221669 28992352104808567]
 [32651505327931493 30399778528231525 32370056121024609      519698382894]]


In [12]:
# numpy array 생성 함수 2

x = [1,2,3]
a = np.asarray(x)
print (a)




[1 2 3]


In [13]:
# numpy array 생성 함수 3

x1 = range(10, 20, 2)       # 반복자 반환 ( 값의 목록을 반환하지 않습니다 )
x2 = np.arange(10, 20, 2)   # numpy array 형식의 값 목록을 반환
print(x1) # 반복자이기 때문에 바로 출력할 수 없습니다. - 반복문으로 각 값을 읽어야 합니다.
print(list(x1))
print(x2) 

range(10, 20, 2)
[10, 12, 14, 16, 18]
[10 12 14 16 18]


In [14]:
# numpy array 생성 함수 4

a = np.linspace(1.0, 2.0, num=5)
print (a)

x = np.linspace(10, 20, 5, endpoint=False)
print (x)

x = np.linspace(1, 2, 5, retstep=True)
print (x) 


[1.   1.25 1.5  1.75 2.  ]
[10. 12. 14. 16. 18.]
(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), np.float64(0.25))


In [ ]:
# 인덱싱과 슬라이싱 1

a = np.arange(10)
s = slice(2,7,2) # 슬라이싱 규칙 만들기 (2에서 7까지 2씩 증가)
print(a)
print(a[s])

# a = np.arange(10) # == np.arange(0, 10)
a = np.arange(0, 10)
b = a[2:7:2] # [2:7:2] == slice(2, 7, 2)
print (b)

a = np.arange(10)
print(a[4])


[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[2 4 6]
4


In [23]:
# 인덱싱과 슬라이싱 2

d = [[1,2,3],[3,4,5],[4,5,6]]
a = np.array(d)

print(d)
print(a)

# 1. 1차원에서는 인덱싱 사용 방법 동일
print(d[1], a[1])

# 2. 1차원에서는 슬라이싱 사용 방법 동일
print(d[1:], a[1:])

# 3. 2차원 이상에서 인덱싱 사용 방법 차이
print(d[1][2], a[1, 2])

# 4. 2차원 이상에서 슬라이싱 사용 방법 차이
print(d[1][1:], a[1, 1:])

# 5. 2차원 이상에서 슬라이싱 사용 방법 차이 2 - 
print(d[1:][1:])
print(a[1:, 1:])

[[1, 2, 3], [3, 4, 5], [4, 5, 6]]
[[1 2 3]
 [3 4 5]
 [4 5 6]]
[3, 4, 5] [3 4 5]
[[3, 4, 5], [4, 5, 6]] [[3 4 5]
 [4 5 6]]
5 5
[4, 5] [4 5]
[[4, 5, 6]]
[[4 5]
 [5 6]]
